-- NRDOT Oracle DB receiver monitoring user.
-- Runs as / as sysdba in CDB$ROOT (gvenzl entrypoint executes .sql files via sqlplus / as sysdba).
-- c## prefix required for CDB common users. CONTAINER=ALL grants access across all PDBs.

CREATE USER c##nrdot IDENTIFIED BY "NrdotMonitor1";

ALTER USER c##nrdot SET CONTAINER_DATA=ALL CONTAINER=CURRENT;
GRANT CREATE SESSION TO c##nrdot CONTAINER=ALL;
GRANT SET CONTAINER  TO c##nrdot CONTAINER=ALL;
GRANT CONNECT        TO c##nrdot CONTAINER=ALL;

GRANT SELECT ON SYS.V_$SESSION               TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$SYSSTAT               TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$SESSTAT               TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$STATNAME              TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$SYSTEM_EVENT          TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$SHARED_SERVER         TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DISPATCHER            TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$CIRCUIT               TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$RESOURCE_LIMIT        TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$LOCK                  TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DATABASE              TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$PARAMETER             TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$SQLAREA               TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$SQL                   TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$SQL_PLAN              TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.V_$PDBS                  TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$INSTANCE             TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$SGA                  TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$SESSTAT              TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$STATNAME             TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$SYSSTAT              TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$SQLAREA              TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$LIBRARYCACHE         TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$ROWCACHE             TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$PGASTAT              TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$CONTAINERS           TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$PDBS                 TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$CON_SYSMETRIC        TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$SYSMETRIC            TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$FILESTAT             TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$SYSTEM_EVENT         TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$ACTIVE_SERVICES      TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$SESSION              TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$SESSION_WAIT         TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON SYS.GV_$ROLLSTAT             TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON DBA_OBJECTS                  TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON DBA_TABLESPACES              TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON DBA_TABLESPACE_USAGE_METRICS TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON DBA_DATA_FILES               TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON DBA_USERS                    TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON CDB_SERVICES                 TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON CDB_DATA_FILES               TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON CDB_TABLESPACE_USAGE_METRICS TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON CDB_USERS                    TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON CDB_PDBS                     TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON ALL_USERS                    TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON ALL_VIEWS                    TO c##nrdot CONTAINER=ALL;
GRANT SELECT ON GLOBAL_NAME                  TO c##nrdot CONTAINER=ALL;

COMMIT;
