apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFMTCCAxmgAwIBAgIUYUpWnH9ngi9uOusI7k9KQ3cU37MwDQYJKoZIhvcNAQEL
    BQAwKDETMBEGA1UEAwwKR2F0ZXdheSBDQTERMA8GA1UECgwITmV3UmVsaWMwHhcN
    MjYwMzAyMjE1NjMxWhcNMjcwMzAyMjE1NjMxWjAoMRMwEQYDVQQDDApHYXRld2F5
    IENBMREwDwYDVQQKDAhOZXdSZWxpYzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
    AgoCggIBAP3iCW9XqlAXPmO7gKljXYBCGq9duemJShvFfGxO3ibiczP8MkkByixr
    ZUgO1vKAUNnyt2Ctc68pKKy6RzTTGTwVFtB9FFU7zhHb1qMnYjSJpmCvR3xybpCm
    jePsOKgdzm19TUebT0M6cuTGicGj83FV/+PJeBPkjVPIibyfCV9ZsbWNRv7SmxTF
    mp9Wpq2yaD9F1f5L2UtEabZ83sJLXKFIg0ffhAkVHBqsOYIKxlgpuqw6D5fSHRl6
    hzSU17E6Zeh6nZAPDoACxw7moFKJhhO2WkdsPNyiJLBKj5LUui1PikAdbI50xoQ4
    KuHmOSf2IC6FdmOyxkBJId8WICKSgzaaEVQ/Uk7avXiIOKBgzpx+bMNktu8uaAz5
    SBLtv/BPcnuOublVvJZdpyOFBaqUH7w93VAXGcuOYfhwP8d6yn/A3mSAxF5M4MGQ
    frejgEyKxhtlcIsTDVNQtF22h5YfZF1DLprAWYXgzTuUastLr6dcrEh7Yi0q7AqH
    efCaLORNM/FWii9IlEb36/yx8wFnfcdgWLMVCKJG/hg5fYCo6HrPBfUdE5SrNxRK
    BQ9yANEpyxzTKqB3F+YnNsskhF+Z3TvExtiHYYh2xCEm9HoM9Z6/7pV2xY2YnBJC
    /6xAwvDMpqfNkgsJ6pr+BzRtdkzXu6OuCNigwteFRy+IWLc6DV4tAgMBAAGjUzBR
    MB0GA1UdDgQWBBTxTk8PKWOHrzRfq+gxelf2MoyyZDAfBgNVHSMEGDAWgBTxTk8P
    KWOHrzRfq+gxelf2MoyyZDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
    A4ICAQAJEOz7FalmxADkdcgC47LsX8907k2R7rxatOsLj51RH5auxGMoz3NS3VP1
    w+0IYbWbsUbGA9IWOHBYOvRy4nlg1cfmvMIIzQ92VrJQwjU1hb99zwlPXMmZFa59
    9XobfOdBIhpRO/NviD7K7Cd8VmIc01DNTdMOAmiGcydb0K4ezwtdL24akD++JlQA
    71/HHpzXvPiceBYO4yjhWPNuIZyvkFUuSpsSQTjkx/CXHa04lznfGwU2XCm11fbz
    aLU48KxIwC9woI26YA9lwdx1Fk2HMbfuv5E43UGcB1+e8XHS3yBBsUvUk+EtCaxg
    MLZDWSufapTqrcMbgVHDMCT1PwVneadyNiQB1YBS0KFM5LF6GEpBbCdoSsoCjc0L
    97aR0SfAYADHIPB34ns33YZKdxDKdSJJlPlyWXrK8dgpNQsT6KcbdKgNn752hEw1
    H+2TXuEFupqYgGYayXNkPzf03WNP+OAN4HaTmPXZtWUMr6cjze020hnwpU+gLLRR
    9WTnLYWVZ+CmC5hRhzplZvWslLr8MSeiq3xQVLFAfc9We6DnRrc1eEkxUCKWJfu6
    eqRZDG/u4yRHRQsdgG9jKuM5njSLLs9gWlyAeyFg3HbEKv55PEMF4EIRrV4HXxLd
    7dTl8ai52zeYjjChTsDkLgYq2nF7obKiNJr/nPSBes/1qQRffA==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: gateway-ca-cert
  namespace: prod
apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFMTCCAxmgAwIBAgIUYUpWnH9ngi9uOusI7k9KQ3cU37MwDQYJKoZIhvcNAQEL
    BQAwKDETMBEGA1UEAwwKR2F0ZXdheSBDQTERMA8GA1UECgwITmV3UmVsaWMwHhcN
    MjYwMzAyMjE1NjMxWhcNMjcwMzAyMjE1NjMxWjAoMRMwEQYDVQQDDApHYXRld2F5
    IENBMREwDwYDVQQKDAhOZXdSZWxpYzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
    AgoCggIBAP3iCW9XqlAXPmO7gKljXYBCGq9duemJShvFfGxO3ibiczP8MkkByixr
    ZUgO1vKAUNnyt2Ctc68pKKy6RzTTGTwVFtB9FFU7zhHb1qMnYjSJpmCvR3xybpCm
    jePsOKgdzm19TUebT0M6cuTGicGj83FV/+PJeBPkjVPIibyfCV9ZsbWNRv7SmxTF
    mp9Wpq2yaD9F1f5L2UtEabZ83sJLXKFIg0ffhAkVHBqsOYIKxlgpuqw6D5fSHRl6
    hzSU17E6Zeh6nZAPDoACxw7moFKJhhO2WkdsPNyiJLBKj5LUui1PikAdbI50xoQ4
    KuHmOSf2IC6FdmOyxkBJId8WICKSgzaaEVQ/Uk7avXiIOKBgzpx+bMNktu8uaAz5
    SBLtv/BPcnuOublVvJZdpyOFBaqUH7w93VAXGcuOYfhwP8d6yn/A3mSAxF5M4MGQ
    frejgEyKxhtlcIsTDVNQtF22h5YfZF1DLprAWYXgzTuUastLr6dcrEh7Yi0q7AqH
    efCaLORNM/FWii9IlEb36/yx8wFnfcdgWLMVCKJG/hg5fYCo6HrPBfUdE5SrNxRK
    BQ9yANEpyxzTKqB3F+YnNsskhF+Z3TvExtiHYYh2xCEm9HoM9Z6/7pV2xY2YnBJC
    /6xAwvDMpqfNkgsJ6pr+BzRtdkzXu6OuCNigwteFRy+IWLc6DV4tAgMBAAGjUzBR
    MB0GA1UdDgQWBBTxTk8PKWOHrzRfq+gxelf2MoyyZDAfBgNVHSMEGDAWgBTxTk8P
    KWOHrzRfq+gxelf2MoyyZDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
    A4ICAQAJEOz7FalmxADkdcgC47LsX8907k2R7rxatOsLj51RH5auxGMoz3NS3VP1
    w+0IYbWbsUbGA9IWOHBYOvRy4nlg1cfmvMIIzQ92VrJQwjU1hb99zwlPXMmZFa59
    9XobfOdBIhpRO/NviD7K7Cd8VmIc01DNTdMOAmiGcydb0K4ezwtdL24akD++JlQA
    71/HHpzXvPiceBYO4yjhWPNuIZyvkFUuSpsSQTjkx/CXHa04lznfGwU2XCm11fbz
    aLU48KxIwC9woI26YA9lwdx1Fk2HMbfuv5E43UGcB1+e8XHS3yBBsUvUk+EtCaxg
    MLZDWSufapTqrcMbgVHDMCT1PwVneadyNiQB1YBS0KFM5LF6GEpBbCdoSsoCjc0L
    97aR0SfAYADHIPB34ns33YZKdxDKdSJJlPlyWXrK8dgpNQsT6KcbdKgNn752hEw1
    H+2TXuEFupqYgGYayXNkPzf03WNP+OAN4HaTmPXZtWUMr6cjze020hnwpU+gLLRR
    9WTnLYWVZ+CmC5hRhzplZvWslLr8MSeiq3xQVLFAfc9We6DnRrc1eEkxUCKWJfu6
    eqRZDG/u4yRHRQsdgG9jKuM5njSLLs9gWlyAeyFg3HbEKv55PEMF4EIRrV4HXxLd
    7dTl8ai52zeYjjChTsDkLgYq2nF7obKiNJr/nPSBes/1qQRffA==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: gateway-ca-cert
  namespace: newrelic
