apiVersion: newrelic.com/v1alpha1
kind: Instrumentation
metadata:
  name: newrelic-instrumentation
  namespace: prod
spec:
  java:
    image: newrelic/newrelic-java-init:latest
    env:
      - name: NEW_RELIC_APP_NAME
        value: "GCP High Volume - Java Apps"
      - name: NEW_RELIC_LICENSE_KEY
        valueFrom:
          secretKeyRef:
            name: newrelic-license
            key: license-key
      - name: NEW_RELIC_LABELS
        value: "environment:prod;cluster:gcp-high-volume-cluster"
