name: Trigger Lambda Functions

on:
  workflow_dispatch:
  schedule:
    # Run every 20 minutes
    - cron: "*/10 * * * *"

jobs:
  invoke-lambdas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure credentials
      id: credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION_RUBY_LAMBDA }}

# CreateItemFunction
# GetAllItemsFunction
# DeleteItemFunction
# GetItemByIdFunction
# UpdateItemFunction

    - name: GetAllItems
      run: |
        aws lambda invoke --function-name GetAllItemsFunction --payload '{}' response.json
        cat response.json
      
    - name: CreateItem
      run: |
        encodedPayload=$(echo '{"body": {"id": "1", "name": "test"}}' | base64)
        aws lambda invoke --function-name CreateItemFunction --payload "$encodedPayload" response.json
        cat response.json

    - name: DeleteItem
      run: |
        encodedPayload=$(echo '{"pathParameters": {"id": "1"}}' | base64)
        aws lambda invoke --function-name DeleteItemFunction --payload "$encodedPayload" response.json
        cat response.json

    # Add additional steps here for more Lambda functions as needed
