name: Trigger Lambda Functions

on:
  schedule:
    # Run every 20 minutes
    - cron: "*/10 * * * *"

jobs:
  invoke-lambdas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-cli@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

# CreateItemFunction
# GetAllItemsFunction
# DeleteItemFunction
# GetItemByIdFunction
# UpdateItemFunction

    - name: Invoke Lambda Function 1
      run: |
        aws lambda invoke --function-name GetAllItemsFunction --payload '{}' response.json
        cat response.json
      
    - name: Invoke Lambda Function 2
      run: |
        aws lambda invoke --function-name CreateItemFunction --payload '{"body": "{\"id\": \"1\",\"name\": \"test\"}"}' response.json
        cat response.json

    # Add additional steps here for more Lambda functions as needed
